# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-ExpandAliases
version:      0.46
version_from: ExpandAliases.pm
installdirs:  site
requires:
    IO::File:                      

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
